version: "3.8"

networks:
  bie-network:

services:
  # Frontend container
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: ghcr.io/amosproj/amos2024ss04-building-information-enhancer-frontend
    environment:
      - HOST=frontend
      - PORT=80
    ports:
      - 8080:80

  # Backend containers
  app:
    build:
      context: ./backend/src/BIE.Core
      dockerfile: Dockerfile
    container_name: app
    environment:
    - ASPNETCORE_ENVIRONMENT=Development #Need to be production for prod env
    - DB_NAME=BIEDB
    - DB_PASSWORD=MyPass@1234
    - DB_SERVER=db
    - DB_USERNAME=sa
    - DB_TYPE=SQL
    - TRUSTED=False
    ports:
      - 8081:80
    networks:
      - bie-network
    depends_on:
      - db


  datapipeline:
    build:
      context: ./backend/src/BIE.DataPipeline
      dockerfile: Dockerfile
    environment:
    - DB_NAME=BIEDB
    - DB_PASSWORD=MyPass@1234
    - DB_SERVER=db
    - DB_USERNAME=sa
    - DB_TYPE=SQL
    - TRUSTED=False
    container_name: datapipeline
    networks:
      - bie-network
    depends_on:
    - db
  db:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    networks:
      - bie-network
    volumes:
      - bie-mssqldata:/var/opt/mssql

volumes:
    bie-mssqldata:
