version: "3.8"
services:
  # Frontend container
  react-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    image: ghcr.io/corgam/bie-frontend
    environment:
      - HOST=${REACT_FRONTEND_HOST}
      - PORT=${REACT_FRONTEND_PORT}
    ports:
      - "${REACT_FRONTEND_PORT}:${REACT_FRONTEND_PORT}"

  # Backend container
  backend:
    build:
      context: ./backend/src/BIE.Core
      dockerfile: Dockerfile
    container_name: backend
    image: ghcr.io/corgam/bie-backend
    environment:
      - HOST=${BACKEND_HOST}
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
