services:
  # Frontend - Apache HTTP server (React + Typescript)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: ghcr.io/amosproj/amos2024ss04-building-information-enhancer-frontend
    environment:
      - HOST=${FRONTEND_HOST}
      - PORT=${FRONTEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}

  # API Gateway for listening for FE requests
  api-gateway:
    build:
      context: ./backend/src/BIE.Core
      dockerfile: Dockerfile
    container_name: api-gateway
    image: ghcr.io/amosproj/amos2024ss04-building-information-enhancer-api-gateway
    environment:
      - ASPNETCORE_ENVIRONMENT=${ENVIRONMENT_STAGE} # Needs to be changed to `Production` for production env.
      - DB_NAME=BIEDB
      - DB_PASSWORD=MyPass@1234
      - DB_SERVER=sql-db
      - DB_USERNAME=sa
      - DB_TYPE=SQL
      - TRUSTED=False
    ports:
      - ${BACKEND_PORT}:80
    networks:
      - bie-network
    depends_on:
      - sql-db

  ## Data Pipeline for ingesting the datasets
  datapipeline:
    build:
      context: ./backend/src/BIE.DataPipeline
      dockerfile: Dockerfile
    environment:
      - DB_NAME=BIEDB
      - DB_PASSWORD=MyPass@1234
      - DB_SERVER=sql-db
      - DB_USERNAME=sa
      - DB_TYPE=SQL
      - TRUSTED=False
    container_name: datapipeline
    networks:
      - bie-network
    depends_on:
      - sql-db

  ## Main SQL DB for storing the datasets
  sql-db:
    build:
      context: ./backend/database
      dockerfile: Dockerfile
    networks:
      - bie-network
    volumes:
      - bie-mssqldata:/var/opt/mssql

volumes:
  bie-mssqldata:

networks:
  bie-network:
