services:
  # Frontend container
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    image: ghcr.io/amosproj/amos2024ss04-building-information-enhancer-frontend
    environment:
      - HOST=${FRONTEND_HOST}
      - PORT=${FRONTEND_PORT}
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"

  # Backend container
  backend:
    build:
      context: ./backend/src/BIE.Core
      dockerfile: Dockerfile
    container_name: backend
    image: ghcr.io/amosproj/amos2024ss04-building-information-enhancer-backend
    environment:
      - HOST=${BACKEND_HOST}
      - PORT=${BACKEND_PORT}
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
