name: Backend - CI

on:
  pull_request:
    branches:
      - sprint-release
      - main
    paths:
      - "backend/**"

jobs:
  linting:
    name: Check linting
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.1.0

      - name: Restore dependencies
        run: dotnet restore
        working-directory: backend\src\BIE.DataPipeline

      - name: Linting
        run: dotnet format BIE.DataPipeline.sln
        working-directory: backend\src\BIE.DataPipeline

  tests:
    needs: linting
    name: Run Tests
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.1.0

      - name: Restore dependencies
        run: dotnet restore
        working-directory: backend\src\BIE.DataPipeline

      - name: Build required Libraries
        run: dotnet build "./BieMetadata.csproj" -c Release
        working-directory: backend\lib\BieMetadata

      - name: Run unit tests
        run: dotnet test ".\src\BIE.DataPipeline"
        working-directory: backend
