name: Backend Unittest

on: push

jobs:
  tests:
    name: Unit Testing
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.1.0
        
      - name: Restore dependencies
        run: dotnet restore
        working-directory: backend\src\BIE.DataPipeline
      
      - name: Run unit tests 
        run: dotnet test
        working-directory: backend\src\BIE.DataPipeline