name: Backend - CI

on:
  pull_request:
    branches:
      - sprint-release
      - main
    paths:
      - "backend/**"
  push:
    branches:
      - '**'

jobs:
  linting:
    name: Check linting
    runs-on: windows-latest

    steps:
      - name: Echo Linting
        uses: dotnet/code-analysis@v1
        id: code-analysis
        with:
          solutions: backend\BIE.Core.sln;backend\BIE.DataPipeline.sln
          build-breaking: false
          all-categories: all

  tests:
    needs: linting
    name: Run Tests
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2.1.0
        
      - name: Restore dependencies
        run: dotnet restore
        working-directory: backend\src\BIE.DataPipeline
      
      - name: Run unit tests 
        run: dotnet test
        working-directory: backend\src\BIE.DataPipeline
