name: Build Docker Compose

on:
  pull_request:
    branches:
      - sprint-release
      - main
    paths:
      - "backend/**"
      - "frontend/**"

jobs:
  build:
    name: Build the Docker Image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Image
        run: docker compose build --pull
