name: Frontend - Tests

on:
  pull_request:
    branches:
      - sprint-release
      - main
    paths:
      - "frontend/**"
  push:
    branches:
      - sprint-release
      - main
    paths:
      - "frontend/**"

jobs:
  linting:
    name: Check linting
    runs-on: ubuntu-latest

    steps:
      - name: Echo Linting
        run: echo "linting"

  tests:
    needs: linting
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Echo Test
        run: echo "test"
